### ISSUE TITLE
Add example of use with custom UI components

### ISSUE THREAD

**Issue by TylerRick** [emolifeconnect/react-form-state-manager#2]
I'm currently comparing this hook with https://react-hook-form.com/ and trying to decide which one will be flexible enough to be a better choice long-term. 

Can you hook this hook in to work with any arbitrary UI component?

The `react-hook-form` [API](https://react-hook-form.com/api/) has a [`setValue`](https://react-hook-form.com/api/#setValue) function you can use in the `onChange` handler of any component to tie it into the form state, as seen in https://codesandbox.io/s/72j69vnk1x, for example. Is there a way to do that with `react-form-state-manager` too?

**Comment by TylerRick** [comment]
Ah, I see now that `form.setParsedValue` is a public method on `form`, so it should be as simple as this:
```jsx
          <Select
            className="reactSelect"
            name="filters"
            placeholder="Filters"
            options={options}
            value={get(form.values, 'reactSelect', [])}
            onChange={(selectedOption) => form.setParsedValue('reactSelect', selectedOption)}
            isMulti
          />
```
That's actually a lot simpler than the way you have to do it with `react-hook-form`.

I'm really impressed by this library so far. The only possible disadvantage is that it only works with controlled inputs, whereas `react-hook-form` can work with _uncontrolled_ components (and they seem to recommend doing so for better performance) too. But working with controlled input components (where the `form.values` state is the single source of truth) does make things simpler and easier to reason about... Maybe that is more important, until such point as you run into performance problems?

**Comment by joostbaptist** [comment]
Hey Tyler, 

That looks about right to me. Instead of `get(form.values, 'reactSelect', [])` you could use `form.getParsedValue('filters') || []`. By the way, does your `onChange` callback receive just the selected option, or the new, complete list of selected options? In the first case, you would probably need to implement an `onChange` handler like this:

```tsx
const onChange = (name, value) => {
    const selected = form.getParsedValue(name) || [];
    const index = form.findIndex(selected, value);

    if (index > -1) {
        form.delete(name, index);
    } else {
        form.append(name, value);
    }
}
```

Hope this helps!

Since this package is specifically aimed at controlled inputs, I have not thought about implementing support for uncontrolled inputs... I'm not sure when using uncontrolled inputs can be beneficial as I have never run into form related performance issues.
