### ISSUE TITLE
Feature parity with react-use-form-state?

### ISSUE THREAD

**Issue by TylerRick** [emolifeconnect/react-form-state-manager#3]
**How does one choose a form library to use for one's React forms?**

It's hard to choose a form library because you have to pick only _one_ of them to use in your form, and they each of their own unique advantages!

Perhaps `react-form-state-manager` is different enough from other major options like [`react-hook-form`](https://github.com/bluebill1049/react-hook-form) and [`react-final-form`](https://github.com/final-form/react-final-form) to really compare directly with them. But, in particular, how does one choose between [`react-use-form-state`](https://github.com/wsmd/react-use-form-state) and `react-form-state-manager`? They both share a similar philosophy, but also some subtle difference.

Do you think parity with `react-use-form-state` might be an eventual goal?
(Ideally, I even wish that this project could be a _fork_ of or _extension_ for `react-use-form-state`, so that all the features, work, and compatibility from that project came for "free", but I'm guessing you've already considered that option?)

## Unique features of [`react-use-form-state`](https://github.com/wsmd/react-use-form-state):
- Ability to pass in a custom validator directly: `validate: value => validateUsername(value)`
  - (But can do similar in `react-form-state-manager` with a custom pipeline)
- [`input.label()`](https://github.com/wsmd/react-use-form-state#labels) and `formOptions.withIds` 
- Explicit support for custom controls: `input.raw()`
- Appears to have better [TypeScript support](https://github.com/wsmd/react-use-form-state#working-with-typescript)
- `formState.touched` — an object indicating whether the input was touched (focused) by the user

## Common/similar features 
- Similar API: props that you spread into an actual `<input>` element: `{...input.text({...})}`
- `formState.setField` vs. `form.setParsedValue`
- `formState.validity` vs. `form.valid`

## Unique features of `react-form-state-manager`:
- Conveniently edit nested objects/arrays using dot notation: `<input {...form.text(`products.${index}.title`)} />`.
  - (Most important feature for me)
- Comes with utility methods that cover many common use cases, like set, append, prepend, moveUp, moveDown, delete, reset and more.
- Input pipelines allowing you to separate formatting and internal state representation
  - `form.formattedValues`

Even between these 2 similar options, it's tough to pick a winner. Wouldn't it be great if you could have all the features from both projects? :)

In the end though, it may not matter for me, since I think I'm leaning towards using [`react-final-form`](https://github.com/final-form/react-final-form).

**Comment by joostbaptist** [comment]
Hey Tyler,

That looks like a pretty good comparison to me! 

You're right, this package was inspired by react-use-form-state, which is why they look very similar. I started building it for a (time sensitive) project months ago, not long after react-use-form-state was published. At the time, react-use-form-state did not contain all the features I needed/liked (and still doesn't). I really like having separate 'internal' and 'external' states. For example, it's possible to represent every date as YYYY-MM-DD under the hood, while showing it as DD-MM-YYYY to the user. This greatly simplifies further computation based on date values, as they are all normalized. This is a pretty fundamental difference with react-use-form-state. Building my own package was the fastest way to achieve the things I needed.

I specifically did not want to use a package based on components, because it seems so much more complicated to customize them (basically, you have to rely on the package's support for customization).
